server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /data/ {
        proxy_pass http://ultrafeeder/data/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
