server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /data/ {
        proxy_pass http://ultrafeeder/data/;
    }

    location /external/ {
        resolver 127.0.0.11 valid=30s;
        proxy_ssl_server_name on;
        proxy_set_header Host opendata.adsb.fi;
        proxy_pass https://opendata.adsb.fi/api/v3/;
    }

    location /stats-api/ {
        proxy_pass http://radar-stats:8090/api/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
